### ISSUE TITLE
Galois fields

### ISSUE THREAD

**Issue by JeWaVe** [aerobus-open-source/aerobus#9]
Add a representation of F4 and compute polynomials over it as an example of possible extensions. 
Here are the tables for F4

![image](https://github.com/aerobus-open-source/aerobus/assets/11440561/08ef01fb-c0ca-4b4e-bd78-645e8b6a0662)

**Comment by JeWaVe** [comment]
actually : implement Cantor Zassenhaus and yield a compile time representation of GF(p^n)

**Comment by tchaumeny** [comment]
That might be of interest to you https://arxiv.org/abs/2107.02257

**Comment by JeWaVe** [comment]
Thank you so much.

Envoyé depuis Proton Mail mobile

-------- Message d'origine --------

**Comment by JeWaVe** [comment]
In the end, I chose to take a precomputed table
